name: Build and test maze roamer on windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with: 
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run multi-line script
      shell: pwsh
      run: ci/github-ci-windows.ps1 test-maze-roamer-build
